[install]
is_configured = 0
state = enabled
build = 1

[ui]
is_visible = 1
label = BankStack SOC
description = Bangladesh Banking SOC — Wazuh + Splunk Unified Security Monitoring

[launcher]
author = BankStack
version = 1.0.0

[package]
check_for_updates = 0
