# ================================================================
# BankStack Splunk Indexes
# ================================================================

[bankstack_wazuh]
coldPath = $SPLUNK_DB/bankstack_wazuh/colddb
homePath = $SPLUNK_DB/bankstack_wazuh/db
thawedPath = $SPLUNK_DB/bankstack_wazuh/thaweddb
maxTotalDataSizeMB = 5120

[bankstack_banking]
coldPath = $SPLUNK_DB/bankstack_banking/colddb
homePath = $SPLUNK_DB/bankstack_banking/db
thawedPath = $SPLUNK_DB/bankstack_banking/thaweddb
maxTotalDataSizeMB = 5120
