# ================================================================
# BankStack Splunk Inputs — Receive Wazuh Alerts via Syslog
# ================================================================

[udp://9515]
connection_host = dns
sourcetype = wazuh-alerts
index = bankstack_wazuh
disabled = 0

[http://bankstack_hec]
token = a1b2c3d4-e5f6-7890-abcd-ef1234567890
sourcetype = bankstack:simulator
index = bankstack_banking
disabled = 0
