# ================================================================
# BankStack Splunk Props — Field Extraction
# ================================================================

[wazuh-alerts]
SHOULD_LINEMERGE = false
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 30
KV_MODE = json
TRUNCATE = 65536

[bankstack:simulator]
SHOULD_LINEMERGE = false
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
KV_MODE = json
TRUNCATE = 65536

[bankstack:cbs]
SHOULD_LINEMERGE = false
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
KV_MODE = json

[bankstack:swift]
SHOULD_LINEMERGE = false
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
KV_MODE = json

[bankstack:mfs]
SHOULD_LINEMERGE = false
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
KV_MODE = json

[bankstack:beftn]
SHOULD_LINEMERGE = false
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
KV_MODE = json
