# ================================================================
# BankStack Splunk Transforms
# ================================================================

[bd_bank_codes]
filename = bd_bank_codes.csv

[mfs_providers]
filename = mfs_providers.csv

[bankstack_wazuh_index]
REGEX = .
DEST_KEY = _MetaData:Index
FORMAT = bankstack_wazuh

[bankstack_banking_index]
REGEX = .
DEST_KEY = _MetaData:Index
FORMAT = bankstack_banking
